debug: false
app_name: social-network
app_env: dev

http:
  port: 80
  domain:

infrastructure:
  mysql:
    address: 127.0.0.1:6603
    user: appuser
    password: pass
    database: appdb
    replicas:
      - 127.0.0.1:6603

auth:
  token-secret: my-app-secret
  accessTTL: 1h
  refresTTL: 30h
