debug: false
app_name: social-network
app_env: dev

http:
  port: 80
  domain:

mysql:
  master:
    host: mysqldb
    port: 3306
    user: appuser
    password: pass
    database: appdb
  slaves:
    - host: mysqldb
      port: 3306
      user: appuser
      password: pass
      database: appdb
    - host: mysqldb
      port: 3306
      user: appuser
      password: pass
      database: appdb

auth:
  token-secret: my-app-secret
  accessTTL: 1h
  refresTTL: 30h
