version: '3.8'

networks:
  social-app-net:
    name: social-app-net
    driver: bridge

services:
  backend:
    image: backend:latest
    build: ./backend
    expose:
      - ${BACKEND_INTERNAL_PORT}
    depends_on:
      - mysqldb
    networks:
      - social-app-net

  haproxy:
    image: "haproxy:2.2-alpine"
    ports:
      - 80:80
      - 8888:8888
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mysqldb
      - backend
    networks:
      - social-app-net
